trigger:
- main

pool: local-agent

resources:
- repo: self

variables:
  - group: test-api
  - name: nodeEnv
    value: $[variables.NODE_ENV]
  
  - group: test-api
  - name: nodePort
    value: $[variables.NODE_PORT]

parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "test-api"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "var=$(nodeEnv)"
    - script: |
        echo "var=$(nodePort)"

