trigger:
- main

pool: local-agent

resources:
- repo: self

variables:
  - group: test-api
  - name: nodeEnv
    value: $[variables.NODE_ENV]
  
  - group: test-api
  - name: nodePort
    value: $[variables.NODE_PORT]

parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "test-api"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "var=$(nodeEnv)"
    - script: |
        echo "var=$(nodePort)"
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: ${{ parameters.imageName }}
        command: build
        containerRegistry: 'registryConnection'
        dockerfile: "**/qa.dockerfile"
        tags: ${{ parameters.tag }}
        arguments: '--build-arg NODE_ENV=$(nodeEnv) NODE_PORT=$(nodePort)'
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'registryConnection'
        repository: ${{ parameters.imageName }}
        tags: |
          ${{ parameters.tag }}